Internal: Used `beforeChange` instead of `change` to force command read-only mode.
ckeditor/ckeditor5-core pull request #128
Opened 2018-05-28 06:58 UTC by oskarwrobel

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Used `beforeChange` instead of `change` to force `Command` read-only mode. Closes https://github.com/ckeditor/ckeditor5-utils/issues/171.

---

### Requires
- https://github.com/ckeditor/ckeditor5-utils/pull/241

2018-05-29 10:49 UTC, oleq requested changes
The change requires tests ;-)

2018-05-29 10:59 UTC, oskarwrobel commented
This functionality is tested https://github.com/ckeditor/ckeditor5-core/blob/6f55c206ffa51af11f14dc1eee00b284d81e1c87/tests/command.js#L69-L100.

2018-05-29 12:03 UTC, Reinmar commented
So why is this change needed? If everything is fine here, then there's no need for a PR. But we know that something is wrong. So let's test it.

2018-05-30 07:06 UTC, oskarwrobel commented
Ok, test is added.

2018-05-30 07:28 UTC, merged